"use strict";
exports.__esModule = true;
var Product_1 = require("./Product");
var ProductService_1 = require("./ProductService");
var _productService = new ProductService_1.ProductSercive();
var result;
result = _productService.getProducts();
result = _productService.getById(2);
var p = new Product_1.Product();
p.name = 'Iphone 12';
p.price = ' 4000';
p.category = 'Phone';
p.id = 2;
_productService.saveProduct(p);
result = _productService.getProducts();
result = _productService.getById(2);
console.log(result);
